import { AgentPmError } from '@agentpm/shared';

import { parseFrontmatter } from './frontmatter.js';

/** Prefix identifying a file AgentPM generated. Never overwrite a file that lacks this marker. */
export const CODEX_AGENT_GENERATED_MARKER =
  '# generated by agentpm from';

export interface CodexAgentTransformResult {
  /** `<snake_case name>.toml`, relative to `.codex/agents/`. */
  fileName: string;
  toml: string;
}

function toSnakeCase(value: string): string {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return slug.length > 0 ? slug : 'agent';
}

function escapeTomlBasicString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

function escapeTomlMultilineBody(value: string): string {
  // A TOML multi-line basic string (delimited by """) cannot contain an
  // unescaped triple-quote. Escaping the final quote of any embedded run
  // breaks up the delimiter sequence without otherwise touching the body.
  return value.replace(/"""/g, '""\\"');
}

/**
 * Transform a Claude agent markdown file (YAML frontmatter + body) into a
 * Codex CLI agent profile TOML file. Pure function: no filesystem access.
 */
export function transformClaudeAgentToCodexToml(
  markdown: string,
): CodexAgentTransformResult {
  const { data, body } = parseFrontmatter(markdown);

  const rawName = typeof data.name === 'string' ? data.name : '';
  if (!rawName.trim()) {
    throw new AgentPmError(
      'Cannot transform a Claude agent to a Codex profile without a frontmatter "name" field.',
    );
  }
  const snakeName = toSnakeCase(rawName);

  const description = typeof data.description === 'string' ? data.description : '';
  const sandboxMode =
    typeof data.sandbox === 'string' && data.sandbox.trim() === 'workspace-write'
      ? 'workspace-write'
      : 'read-only';

  const developerInstructions = escapeTomlMultilineBody(
    body.replace(/^\r?\n+/, '').replace(/\s+$/, ''),
  );

  const toml = [
    `${CODEX_AGENT_GENERATED_MARKER} .claude/agents/${snakeName}.md - do not edit`,
    `name = "${escapeTomlBasicString(snakeName)}"`,
    `description = "${escapeTomlBasicString(description)}"`,
    // Model and reasoning effort intentionally NOT emitted: agents inherit
    // them from the parent Codex session (model entitlements like GPT-5.6
    // vary per account and must never be hard-pinned in generated files).
    `sandbox_mode = "${sandboxMode}"`,
    `developer_instructions = """`,
    developerInstructions,
    `"""`,
    '',
  ].join('\n');

  return {
    fileName: `${snakeName}.toml`,
    toml,
  };
}

/** True when `content` starts with the AgentPM-generated marker comment. */
export function isGeneratedCodexAgentFile(content: string): boolean {
  return content.startsWith(CODEX_AGENT_GENERATED_MARKER);
}
