import { AgentPmError } from '@agentpm/shared';

import { parseFrontmatter } from './frontmatter.js';

/** Marker line identifying a Kimi skill AgentPM generated. Never overwrite a file that lacks it. */
export const KIMI_AGENT_SKILL_GENERATED_MARKER =
  '<!-- generated by agentpm from';

/** Tools an agent may hold and still be delegated to Kimi's read-only `explore` profile. */
const EXPLORE_SAFE_TOOLS = new Set(['read', 'grep', 'glob']);

export interface KimiAgentTransformResult {
  /** `agent-<kebab-case name>`, the skill directory under `.kimi-code/skills/`. */
  dirName: string;
  /** Full `SKILL.md` content for that directory. */
  skillMd: string;
}

function toKebabCase(value: string): string {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug.length > 0 ? slug : 'agent';
}

function parseToolsField(value: unknown): string[] {
  if (typeof value === 'string') {
    return value
      .split(',')
      .map((tool) => tool.trim())
      .filter((tool) => tool.length > 0);
  }
  if (Array.isArray(value)) {
    return value
      .filter((tool): tool is string => typeof tool === 'string')
      .map((tool) => tool.trim())
      .filter((tool) => tool.length > 0);
  }
  return [];
}

/**
 * Pick the Kimi built-in sub-agent profile for a role: `explore` (read-only)
 * when every declared tool is read-only, otherwise `coder`. An agent without
 * a `tools` field gets the unrestricted `coder` profile.
 */
function pickSubagentType(tools: string[]): 'explore' | 'coder' {
  if (tools.length === 0) {
    return 'coder';
  }
  const readOnly = tools.every((tool) =>
    EXPLORE_SAFE_TOOLS.has(tool.toLowerCase()),
  );
  return readOnly ? 'explore' : 'coder';
}

/**
 * Transform a Claude agent markdown file (YAML frontmatter + body) into a
 * Kimi Code delegation skill. Kimi Code has no user-defined sub-agents, so
 * the role is emulated: the generated skill instructs the main agent to
 * spawn Kimi's built-in `Agent` tool with the role brief as the prompt
 * preamble. Pure function: no filesystem access.
 */
export function transformClaudeAgentToKimiSkill(
  markdown: string,
): KimiAgentTransformResult {
  const { data, body } = parseFrontmatter(markdown);

  const rawName = typeof data.name === 'string' ? data.name : '';
  if (!rawName.trim()) {
    throw new AgentPmError(
      'Cannot transform a Claude agent to a Kimi skill without a frontmatter "name" field.',
    );
  }
  const kebabName = toKebabCase(rawName);
  const dirName = `agent-${kebabName}`;

  const description = typeof data.description === 'string' ? data.description : '';
  const subagentType = pickSubagentType(parseToolsField(data.tools));

  const roleBrief = body.replace(/^\r?\n+/, '').replace(/\s+$/, '');

  const skillMd = [
    '---',
    `name: ${dirName}`,
    // JSON string escaping is valid YAML and keeps arbitrary description text safe.
    `description: ${JSON.stringify(description)}`,
    '---',
    `${KIMI_AGENT_SKILL_GENERATED_MARKER} .claude/agents/${kebabName}.md - do not edit -->`,
    '',
    `This skill delegates work to the "${kebabName}" role. Do NOT perform the task`,
    'in the current context. Instead, launch a sub-agent with the Agent tool',
    `(subagent_type: "${subagentType}") and place the role brief below verbatim at`,
    'the start of the sub-agent prompt, followed by the concrete task and all',
    'context the role needs (the sub-agent sees nothing else).',
    '',
    '## Role brief',
    '',
    roleBrief,
    '',
  ].join('\n');

  return { dirName, skillMd };
}

/** True when `content` contains the AgentPM-generated Kimi skill marker. */
export function isGeneratedKimiAgentSkill(content: string): boolean {
  return content.includes(KIMI_AGENT_SKILL_GENERATED_MARKER);
}
